Pt1: Added plugin manager with load/unload support
IlmConnect/IlmConnect pull request #30
Opened 2022-11-24 08:20 UTC by nmosman

Added basic plugin manager functionality for plugins that support load/unload calls. Currently have two test plugins, first one to test load/unload and second one to test loading endpoints from plugins, but that isn't finished yet. Implementation definitely could have been better and with review of PR, open to making changes and will also need to have a discussion on finalizing plugin manifest format, permissions, events and also endpoint loading.

2022-11-24 08:22 UTC, nmosman reviewed
Don't hold back boys, rip it apart. Also still a WIP, and in Part 2 of PR would like to add endpoint functionality.

2022-11-27 22:47 UTC, Aelbannan requested changes
Generally looks good!

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/src/plugin_manager.ts
> +    core : any;      // Where plugin actually sits. NOTE: Plugin name and version sits here too...
If this is bc of the flexible endpoints, maybe switch to objects instead of classes? We want to avoid using `any` as much as possible, using objects would make creating interfaces easy

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/plugins/manifest.ts
> +    endpoints: string [][];
should be `[HttpMethod, string]`

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/plugins/manifest.ts
> +    endpoints: string [][];
Might need to create the HttpMethod type as a string enum

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/plugins/template.ts
> +
no typing for 'endpoint' functions. Could either keep functions, or have a `getEndpoints` function that returns all the endpoint functions

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/src/index.ts
> +			if(method == "GET"){
Switch statement pls

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/src/index.ts
> +				app.get(defaultPrefix + route, endpointFunc.bind(plugin.core));
also, might be moving `defaultPrefix + route` outside bc multiple routes use it

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/src/index.ts
> +async function loadEndpoints(app: Express, pm : PluginManager){
I'm a bit confused about the relationship between this file and `PluginManager`. This file seems to be doing "Plugin Manager" things

2022-11-27 22:47 UTC, Aelbannan commented on plugin_manager/src/plugin_manager.ts
> +        let Plugin = new plugin['default'](); // Probably can do without default index if imported correctly?
Yeah, export using `module.exports`. Can explain if needed

2022-11-29 23:58 UTC, Aelbannan approved these changes

2022-11-29 23:58 UTC, Aelbannan commented on plugin_manager/plugins/manifest.ts
> +type httpMethod = "GET" | "POST" | "PATCH" | "DELETE";  // Add more as needed
Could (Should?) be an enum, but can be changed later

2022-11-30 05:58 UTC, nmosman commented on plugin_manager/plugins/manifest.ts
> +type httpMethod = "GET" | "POST" | "PATCH" | "DELETE";  // Add more as needed
Oh yeah I'll refactor into enum and put into a file for types or something.

2022-11-30 05:58 UTC, merged